---
kind: pipeline
type: docker
name: linux-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: always
  image: rancher/hardened-build-base:v1.15.8b5
  commands:
  - make DRONE_TAG=${DRONE_TAG} image-build-runtime
    #  - make DRONE_TAG=${DRONE_TAG} image-build-builder
    #  - make DRONE_TAG=${DRONE_TAG} image-build-cilium
  volumes:
  - name: docker
    path: /var/run/docker.sock
  environment:
    DOCKER_BUILDKIT: 1

- name: publish
  image: rancher/hardened-build-base:v1.15.8b5
  commands:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - make DRONE_TAG=${DRONE_TAG} image-push-runtime image-manifest-runtime
    #  - make DRONE_TAG=${DRONE_TAG} image-push-builder image-manifest-builder
    #  - make DRONE_TAG=${DRONE_TAG} image-push-cilium image-manifest-cilium
  environment:
    DOCKER_PASSWORD:
      from_secret: docker_password
    DOCKER_USERNAME:
      from_secret: docker_username
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    event:
    - tag

- name: scan
  image: rancher/hardened-build-base:v1.15.8b5
  commands:
  - make DRONE_TAG=${DRONE_TAG} image-scan-runtime
    #  - make DRONE_TAG=${DRONE_TAG} image-scan-builder
    #  - make DRONE_TAG=${DRONE_TAG} image-scan-cilium
  volumes:
  - name: docker
    path: /var/run/docker.sock

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

...
